name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pip install poetry
        make install
      
    - name: Run check
      run: make check
    
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: b1dc72f2ff77b1604b47fc80564f3547d078bc6016e6bfeef5da403fd0653696
      with:
        coverageCommand: make test-coverage
        debug: true
